using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Text;

namespace AttributedDI.SourceGenerator.InterfacesGeneration;

internal static class GeneratedInterfacesCodeEmitter
{
    public static void EmitInterfaces(SourceProductionContext context, ImmutableArray<GeneratedInterfaceInfo> interfacesToGenerate)
    {
        foreach (var interfaceInfo in interfacesToGenerate)
        {
            var source = BuildInterfaceSource(interfaceInfo);
            var hintName = CreateHintName(interfaceInfo);
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildInterfaceSource(GeneratedInterfaceInfo interfaceInfo)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(interfaceInfo.InterfaceNamespace))
        {
            builder.Append("namespace ").Append(interfaceInfo.InterfaceNamespace).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append(interfaceInfo.Accessibility)
            .Append(" interface ")
            .Append(interfaceInfo.InterfaceName)
            .AppendLine();
        builder.AppendLine("{");

        foreach (var member in interfaceInfo.MemberSignatures)
        {
            builder.Append("    ").Append(member);
            if (!member.EndsWith(";", StringComparison.Ordinal))
            {
                builder.Append(';');
            }

            builder.AppendLine();
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string CreateHintName(GeneratedInterfaceInfo interfaceInfo)
    {
        var namespacePart = string.IsNullOrWhiteSpace(interfaceInfo.InterfaceNamespace)
            ? "Global"
            : interfaceInfo.InterfaceNamespace.Replace('.', '_');

        return $"GeneratedInterfaces_{namespacePart}_{interfaceInfo.InterfaceName}.g.cs";
    }
}