using AttributedDI.SourceGenerator.Strategies;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AttributedDI.SourceGenerator;

/// <summary>
/// Emits the final generated registration module and extension method code.
/// </summary>
internal static class CodeEmitter
{
    /// <summary>
    /// Generates a complete registration module file with IServiceModule implementation and extension method in separate files.
    /// </summary>
    /// <param name="context">The source production context for adding generated files.</param>
    /// <param name="moduleName">The name of the module class (e.g., "MyAssemblyModule").</param>
    /// <param name="methodName">The name of the registration method (e.g., "AddMyAssembly").</param>
    /// <param name="assemblyName">The name of the assembly being registered.</param>
    /// <param name="registrations">Service registrations to include.</param>
    public static void EmitRegistrationModule(
        SourceProductionContext context,
        string moduleName,
        string methodName,
        string namespaceName,
        string assemblyName,
        ImmutableArray<RegistrationInfo> registrations)
    {
        // Emit module class
        string moduleSource = EmitModuleClass(moduleName, namespaceName, assemblyName, registrations);
        context.AddSource($"{moduleName}.g.cs", moduleSource);

        // Emit extension methods
        string extensionSource = EmitExtensionMethod(moduleName, methodName, namespaceName, assemblyName);
        context.AddSource($"{moduleName}ServiceCollectionExtensions.g.cs", extensionSource);
    }

    private static string EmitModuleClass(string moduleName, string namespaceName, string assemblyName, ImmutableArray<RegistrationInfo> registrations)
    {
        var sb = new StringBuilder();

        // File header
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine("using AttributedDI;");
        _ = sb.AppendLine();

        _ = sb.AppendLine($"namespace {namespaceName}");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine($"    /// Service registration module for the {assemblyName} assembly.");
        _ = sb.AppendLine("    /// This module registers all services marked with AttributedDI attributes.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine($"    public partial class {moduleName} : IServiceModule");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        /// <summary>");
        _ = sb.AppendLine("        /// Configures services in the dependency injection container.");
        _ = sb.AppendLine("        /// </summary>");
        _ = sb.AppendLine("        /// <param name=\"services\">The service collection to configure.</param>");
        _ = sb.AppendLine("        public virtual void ConfigureServices(IServiceCollection services)");
        _ = sb.AppendLine("        {");

        // Generate service registrations
        ServiceRegistrationStrategy.GenerateCode(sb, registrations);

        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EmitExtensionMethod(string moduleName, string methodName, string namespaceName, string assemblyName)
    {
        var sb = new StringBuilder();

        // File header
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine("using AttributedDI;");
        _ = sb.AppendLine();

        _ = sb.AppendLine($"namespace {namespaceName}");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine($"    /// Extension methods for registering services from the {moduleName} module.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine($"    public static partial class {moduleName}ServiceCollectionExtensions");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        /// <summary>");
        _ = sb.AppendLine($"        /// Registers all services from the {assemblyName} assembly that are marked with registration attributes.");
        _ = sb.AppendLine("        /// </summary>");
        _ = sb.AppendLine("        /// <param name=\"services\">The service collection to add services to.</param>");
        _ = sb.AppendLine("        /// <returns>The service collection for chaining.</returns>");
        _ = sb.AppendLine($"        public static IServiceCollection {methodName}(this IServiceCollection services)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine($"            return services.AddModule<{moduleName}>();");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}