using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;

namespace AttributedDI.SourceGenerator;

internal static class GeneratedAttributesInitializer
{
    private const string GeneratedModuleAttributeSource = """
// <auto-generated/>
#nullable enable

namespace AttributedDI.Generated.Internal
{
    /// <summary>
    /// Marks a generated service module to enable discovery by AttributedDI's source generator.
    /// </summary>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class GeneratedModuleAttribute : global::System.Attribute
    {
    }
}
""";

    public static void EmbedGeneratedAttributes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
        {
            postInitializationContext.AddEmbeddedAttributeDefinition();
            postInitializationContext.AddSource(
                "AttributedDI.Generated.Internal.GeneratedModuleAttribute.g.cs",
                SourceText.From(GeneratedModuleAttributeSource, Encoding.UTF8));
        });
    }
}
