using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;

namespace AttributedDI.SourceGenerator;

internal static class GeneratedAttributesInitializer
{
    private const string ExportsServiceCollectionExtensionAttributeSource = """
// <auto-generated/>
#nullable enable

namespace AttributedDI.Generated.Internal
{
    /// <summary>
    /// Marks a service-collection extension method for discovery by AttributedDI's source generator.
    /// </summary>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    internal sealed class ExportsServiceCollectionExtensionAttribute : global::System.Attribute
    {
        public ExportsServiceCollectionExtensionAttribute(global::System.Type extensionType, string methodName)
        {
            ExtensionType = extensionType;
            MethodName = methodName;
        }

        public global::System.Type ExtensionType { get; }

        public string MethodName { get; }
    }
}
""";

    public static void EmbedGeneratedAttributes(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
        {
            postInitializationContext.AddEmbeddedAttributeDefinition();
            postInitializationContext.AddSource(
                "AttributedDI.Generated.Internal.ExportsServiceCollectionExtensionAttribute.g.cs",
                SourceText.From(ExportsServiceCollectionExtensionAttributeSource, Encoding.UTF8));
        });
    }
}
