<Project>
  <PropertyGroup>
    <IsE2E Condition="'$(IsE2E)' == ''">false</IsE2E>
    <!-- <IsE2E>true</IsE2E> -->
    <AttributedDIPackageVersion Condition="'$(IsE2E)' == 'true'">99.0.0-e2e.*</AttributedDIPackageVersion>
    <!-- Ease the restrictions as these contain test code -->
    <AnalysisMode>Default</AnalysisMode>
  </PropertyGroup>

  <Import Project="..\..\..\src\AttributedDI\AttributedDI.props" Condition="'$(IsE2E)' != 'true'" />

</Project>