<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisMode>Default</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AllModulesRegistration.Core/AllModulesRegistration.Core.csproj" />
  </ItemGroup>

  <!-- AttributedDI references are handled in Directory.Build.props file -->

</Project>