using AttributedDI.SourceGenerator;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace AttributedDI.SourceGenerator.ModuleInitializerGeneration;

internal static class GeneratedModuleInitializerEmitter
{
    public static void EmitModuleInitializer(
        SourceProductionContext context,
        ImmutableArray<GeneratedModuleRegistrationInfo> moduleTypes)
    {
        if (moduleTypes.IsDefaultOrEmpty)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("namespace AttributedDI");
        builder.AppendLine("{");
        GeneratedCodeHelper.AppendGeneratedCodeAttribute(builder, 1);
        builder.AppendLine("    internal static class AttributedDiGeneratedModuleInitializer");
        builder.AppendLine("    {");
        builder.AppendLine("        [ModuleInitializer]");
        GeneratedCodeHelper.AppendGeneratedCodeAttribute(builder, 2);
        builder.AppendLine("        internal static void Initialize()");
        builder.AppendLine("        {");

        foreach (var moduleType in moduleTypes)
        {
            builder.Append("            AttributedDiGeneratedModuleRegistry.Register(typeof(")
                .Append(moduleType.FullyQualifiedTypeName)
                .AppendLine("));");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("AttributedDiGeneratedModuleInitializer.g.cs", builder.ToString());
    }
}