using AttributedDI.SourceGenerator;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Immutable;
using System.Text;

namespace AttributedDI.SourceGenerator.ServiceModulesGeneration;

/// <summary>
/// Emits the final generated service-collection extension code.
/// </summary>
internal static class ServiceCollectionExtensionCodeEmitter
{
    /// <summary>
    /// Generates a complete service-collection extension file with direct registrations.
    /// </summary>
    /// <param name="context">The source production context for adding generated files.</param>
    /// <param name="extensionClassName">The name of the extension class.</param>
    /// <param name="methodName">The name of the registration method.</param>
    /// <param name="namespaceName">The namespace for the generated extension class.</param>
    /// <param name="assemblyName">The name of the assembly being registered.</param>
    /// <param name="registrations">Service registrations to include.</param>
    public static void EmitServiceCollectionExtension(
        SourceProductionContext context,
        string extensionClassName,
        string methodName,
        string namespaceName,
        string assemblyName,
        ImmutableArray<RegistrationInfo> registrations)
    {
        string extensionSource = EmitExtensionMethod(extensionClassName, methodName, namespaceName, assemblyName, registrations);
        context.AddSource(CreateHintName(namespaceName, extensionClassName), extensionSource);
    }

    private static string EmitExtensionMethod(
        string extensionClassName,
        string methodName,
        string namespaceName,
        string assemblyName,
        ImmutableArray<RegistrationInfo> registrations)
    {
        var sb = new StringBuilder();

        // File header
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine();

        string fullyQualifiedTypeName = BuildFullyQualifiedTypeName(namespaceName, extensionClassName);
        _ = sb.AppendLine(
            $"[assembly: global::AttributedDI.Generated.Internal.ExportsServiceCollectionExtensionAttribute(typeof({fullyQualifiedTypeName}), \"{methodName}\")]");
        _ = sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(namespaceName) && !string.Equals(namespaceName, "<global namespace>", StringComparison.Ordinal))
        {
            _ = sb.AppendLine($"namespace {namespaceName}");
            _ = sb.AppendLine("{");
        }

        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine($"    /// Extension methods for registering services from the {assemblyName} assembly.");
        _ = sb.AppendLine("    /// </summary>");
        GeneratedCodeHelper.AppendGeneratedCodeAttribute(sb, 1);
        _ = sb.AppendLine($"    public static partial class {extensionClassName}");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        /// <summary>");
        _ = sb.AppendLine($"        /// Registers all services from the {assemblyName} assembly that are marked with registration attributes.");
        _ = sb.AppendLine("        /// </summary>");
        _ = sb.AppendLine("        /// <param name=\"services\">The service collection to add services to.</param>");
        _ = sb.AppendLine("        /// <returns>The service collection for chaining.</returns>");
        _ = sb.AppendLine($"        public static IServiceCollection {methodName}(this IServiceCollection services)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            ArgumentNullException.ThrowIfNull(services);");
        _ = sb.AppendLine();

        // Generate service registrations
        GenerateCode(sb, registrations);

        _ = sb.AppendLine();
        _ = sb.AppendLine("            return services;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        if (!string.IsNullOrWhiteSpace(namespaceName) && !string.Equals(namespaceName, "<global namespace>", StringComparison.Ordinal))
        {
            _ = sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string CreateHintName(string namespaceName, string typeName)
    {
        var normalized = NormalizeNamespace(namespaceName);
        if (string.IsNullOrWhiteSpace(normalized))
        {
            return $"{typeName}.g.cs";
        }

        return $"{normalized}.{typeName}.g.cs";
    }

    private static string NormalizeNamespace(string? namespaceValue)
    {
        if (string.IsNullOrWhiteSpace(namespaceValue))
        {
            return string.Empty;
        }

        if (string.Equals(namespaceValue, "<global namespace>", StringComparison.Ordinal))
        {
            return string.Empty;
        }

        const string prefix = "global::";
        return namespaceValue!.StartsWith(prefix, StringComparison.Ordinal)
            ? namespaceValue.Substring(prefix.Length)
            : namespaceValue;
    }

    private static string BuildFullyQualifiedTypeName(string namespaceName, string typeName)
    {
        if (string.IsNullOrWhiteSpace(namespaceName) || string.Equals(namespaceName, "<global namespace>", StringComparison.Ordinal))
        {
            return $"global::{typeName}";
        }

        return $"global::{namespaceName}.{typeName}";
    }

    /// <summary>
    /// Generates service registration code.
    /// </summary>
    /// <param name="sb">The string builder to append code to.</param>
    /// <param name="registrations">The registrations to generate code for.</param>
    private static void GenerateCode(StringBuilder sb, ImmutableArray<RegistrationInfo> registrations)
    {
        foreach (var registration in registrations)
        {
            GenerateRegistrationCode(sb, registration);
        }
    }

    private static void GenerateRegistrationCode(StringBuilder sb, RegistrationInfo registration)
    {
        var fullTypeName = registration.IsOpenGeneric
            ? registration.UnboundImplementationTypeName
            : registration.FullyQualifiedTypeName;
        var serviceType = registration.IsOpenGeneric
            ? registration.UnboundServiceTypeFullName ?? registration.ServiceTypeFullName
            : registration.ServiceTypeFullName;
        var lifetime = registration.Lifetime;
        var isKeyed = registration.Key != null;

        if (registration.IsOpenGeneric)
        {
            EmitOpenGenericRegistration(sb, serviceType, fullTypeName, lifetime, isKeyed, registration.Key);
            return;
        }

        if (serviceType is string)
        {
            EmitClosedGenericRegistration(sb, serviceType, fullTypeName, lifetime, isKeyed, registration.Key);
            return;
        }

        EmitClosedSelfRegistration(sb, fullTypeName, lifetime, isKeyed, registration.Key);
    }

    private static void EmitClosedGenericRegistration(StringBuilder sb, string serviceType, string implementationType, string lifetime, bool isKeyed, KeyExpression? key)
    {
        if (!isKeyed)
        {
            _ = sb.AppendLine($"            services.Add{lifetime}<{serviceType}, {implementationType}>();");
            return;
        }

        var keyLiteral = FormatKeyLiteral(key);
        _ = sb.AppendLine($"            services.AddKeyed{lifetime}<{serviceType}, {implementationType}>({keyLiteral});");
    }

    private static void EmitClosedSelfRegistration(StringBuilder sb, string implementationType, string lifetime, bool isKeyed, KeyExpression? key)
    {
        if (!isKeyed)
        {
            _ = sb.AppendLine($"            services.Add{lifetime}<{implementationType}>();");
            return;
        }

        var keyLiteral = FormatKeyLiteral(key);
        _ = sb.AppendLine($"            services.AddKeyed{lifetime}<{implementationType}>({keyLiteral});");
    }

    private static void EmitOpenGenericRegistration(StringBuilder sb, string? serviceType, string implementationType, string lifetime, bool isKeyed, KeyExpression? key)
    {
        if (serviceType is string)
        {
            if (!isKeyed)
            {
                _ = sb.AppendLine($"            services.Add{lifetime}(typeof({serviceType}), typeof({implementationType}));");
                return;
            }

            var keyLiteral = FormatKeyLiteral(key);
            _ = sb.AppendLine($"            services.AddKeyed{lifetime}(typeof({serviceType}), {keyLiteral}, typeof({implementationType}));");
            return;
        }

        if (!isKeyed)
        {
            _ = sb.AppendLine($"            services.Add{lifetime}(typeof({implementationType}));");
            return;
        }

        var selfKeyLiteral = FormatKeyLiteral(key);
        _ = sb.AppendLine($"            services.AddKeyed{lifetime}(typeof({implementationType}), {selfKeyLiteral});");
    }

    /// <summary>
    /// Formats a key value as a C# literal for code generation.
    /// </summary>
    /// <param name="key">The key value to format.</param>
    /// <returns>A string representation of the key suitable for code generation.</returns>
    private static string FormatKeyLiteral(KeyExpression? key)
    {
        return key switch
        {
            null => "null",
            _ => key.Code
        };
    }
}
