//HintName: TestsModule.g.cs
// <auto-generated/>
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using AttributedDI;

namespace Tests
{
    /// <summary>
    /// Service registration module for the Tests assembly.
    /// This module registers all services marked with AttributedDI attributes.
    /// </summary>
    public partial class TestsModule : IServiceModule
    {
        /// <summary>
        /// Configures services in the dependency injection container.
        /// </summary>
        /// <param name="services">The service collection to configure.</param>
        public virtual void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<global::MyApp.Services.OuterService>();
            services.AddTransient<global::MyApp.Services.Internal.InnerService>();
        }
    }
}
