//HintName: MyModule.g.cs
// <auto-generated/>
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using AttributedDI;

namespace Custom.Namespace
{
    /// <summary>
    /// Service registration module for the Tests assembly.
    /// This module registers all services marked with AttributedDI attributes.
    /// </summary>
    public partial class MyModule : IServiceModule
    {
        /// <summary>
        /// Configures services in the dependency injection container.
        /// </summary>
        /// <param name="services">The service collection to configure.</param>
        public virtual void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<global::MyApp.MyService>();
        }
    }
}
