//HintName: MyModuleServiceCollectionExtensions.g.cs
// <auto-generated/>
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using AttributedDI;

namespace Custom.Namespace
{
    /// <summary>
    /// Extension methods for registering services from the MyModule module.
    /// </summary>
    public static partial class MyModuleServiceCollectionExtensions
    {
        /// <summary>
        /// Registers all services from the Tests assembly that are marked with registration attributes.
        /// </summary>
        /// <param name="services">The service collection to add services to.</param>
        /// <returns>The service collection for chaining.</returns>
        public static IServiceCollection AddTheModule(this IServiceCollection services)
        {
            return services.AddModule<MyModule>();
        }
    }
}
