//HintName: ServiceRegistrationExtensions.g.cs
// <auto-generated/>
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;

namespace Tests.Generated
{
    /// <summary>
    /// Extension methods for registering services marked with AttributedDI attributes.
    /// </summary>
    public static partial class ServiceCollectionExtensions
    {
        /// <summary>
        /// Registers all services from the Tests assembly that are marked with registration attributes.
        /// </summary>
        /// <param name="services">The service collection to add services to.</param>
        /// <returns>The service collection for chaining.</returns>
        public static IServiceCollection AddTests(this IServiceCollection services)
        {
            services.AddTransient<global::MyApp.IMyService, global::MyApp.DefaultServiceImpl>();
            services.AddKeyedSingleton<global::MyApp.IMyService, global::MyApp.VersionedServiceImpl>("v1");
            services.AddKeyedSingleton<global::MyApp.IMyService, global::MyApp.VersionedServiceImpl>("v2");
            return services;
        }
    }
}
