//HintName: ServiceRegistrationExtensions.g.cs
// <auto-generated/>
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;

namespace Tests
{
    /// <summary>
    /// Extension methods for registering services marked with AttributedDI attributes.
    /// </summary>
    public static partial class ServiceCollectionExtensions
    {
        /// <summary>
        /// Registers all services from the Tests assembly that are marked with registration attributes.
        /// </summary>
        /// <param name="services">The service collection to add services to.</param>
        /// <returns>The service collection for chaining.</returns>
        public static IServiceCollection AddTests(this IServiceCollection services)
        {
            services.AddKeyedTransient<global::MyApp.IMyService, global::MyApp.PrimaryServiceImpl>("primary");
            services.AddKeyedScoped<global::MyApp.IOtherService, global::MyApp.SecondaryServiceImpl>("secondary");
            return services;
        }
    }
}
