using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace AttributedDI.SourceGenerator.ServiceCollectionExtensionsGeneration;

internal static class AttributedDiServiceCollectionExtensionsEmitter
{
    public static void EmitExtensionMethod(
        SourceProductionContext context,
        ImmutableArray<ExportedServiceCollectionExtensionInfo> extensions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("namespace AttributedDI");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Provides extension methods for <see cref=\"IServiceCollection\"/> to register AttributedDI services.");
        builder.AppendLine("    /// </summary>");
        GeneratedCodeHelper.AppendGeneratedCodeAttribute(builder, 1);
        builder.AppendLine("    public static class AttributedDiGeneratedServiceCollectionExtensions");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Adds AttributedDI services to the collection by invoking all exported extension methods.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        /// <param name=\"services\">The service collection to configure.</param>");
        builder.AppendLine("        /// <returns>The service collection for chaining.</returns>");
        builder.AppendLine("        /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"services\"/> is null.</exception>");
        builder.AppendLine("        public static IServiceCollection AddAttributedDi(this IServiceCollection services)");
        builder.AppendLine("        {");
        builder.AppendLine("            ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine();

        foreach (var extension in extensions)
        {
            builder.Append("            _ = ")
                .Append(extension.FullyQualifiedTypeName)
                .Append('.')
                .Append(extension.MethodName)
                .AppendLine("(services);");
        }

        builder.AppendLine("            return services;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("AttributedDI.AttributedDiGeneratedServiceCollectionExtensions.g.cs", builder.ToString());
    }
}
