using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace AttributedDI.SourceGenerator.ServiceCollectionExtensionsGeneration;

internal static class AttributedDiServiceCollectionExtensionsEmitter
{
    public static void EmitExtensionMethods(
        SourceProductionContext context,
        ImmutableArray<GeneratedModuleRegistrationInfo> moduleTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("namespace AttributedDI");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Provides extension methods for <see cref=\"IServiceCollection\"/> to register AttributedDI modules.");
        builder.AppendLine("    /// </summary>");
        GeneratedCodeHelper.AppendGeneratedCodeAttribute(builder, 1);
        builder.AppendLine("    public static class AttributedDiGeneratedServiceCollectionExtensions");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Adds AttributedDI services to the collection using the provided configuration.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        /// <param name=\"services\">The service collection to configure.</param>");
        builder.AppendLine("        /// <returns>The service collection for chaining.</returns>");
        builder.AppendLine("        /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"services\"/> is null.</exception>");
        builder.AppendLine("        public static IServiceCollection AddAttributedDi(this IServiceCollection services)");
        builder.AppendLine("        {");
        builder.AppendLine("            return AddAttributedDi(services, _ => { });");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Adds AttributedDI services to the collection using the provided configuration.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        /// <param name=\"services\">The service collection to configure.</param>");
        builder.AppendLine("        /// <param name=\"configure\">A callback to configure AttributedDI options.</param>");
        builder.AppendLine("        /// <returns>The service collection for chaining.</returns>");
        builder.AppendLine("        /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"services\"/> or <paramref name=\"configure\"/> is null.</exception>");
        builder.AppendLine("        public static IServiceCollection AddAttributedDi(this IServiceCollection services, Action<AttributedDiOptions> configure)");
        builder.AppendLine("        {");
        builder.AppendLine("            ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine("            ArgumentNullException.ThrowIfNull(configure);");
        builder.AppendLine();
        builder.AppendLine("            AttributedDiOptions opts = new();");
        builder.AppendLine();
        builder.AppendLine("            configure(opts);");
        builder.AppendLine();
        builder.AppendLine("            if (opts.RegisterGeneratedModules)");
        builder.AppendLine("            {");

        foreach (var moduleType in moduleTypes)
        {
            builder.Append("                _ = services.AddModule<")
                .Append(moduleType.FullyQualifiedTypeName)
                .AppendLine(">();");
        }

        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (opts.AdditionalModules.Count > 0)");
        builder.AppendLine("            {");
        builder.AppendLine("                foreach (var module in opts.AdditionalModules)");
        builder.AppendLine("                {");
        builder.AppendLine("                    _ = services.AddModule(module);");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (opts.EnableDeferred)");
        builder.AppendLine("            {");
        builder.AppendLine("                // TODO: Lazy<> support but without allocations");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (opts.EnableOwned)");
        builder.AppendLine("            {");
        builder.AppendLine("                // TODO: enable Owned<> support");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (opts.EnableFactory)");
        builder.AppendLine("            {");
        builder.AppendLine("                // TODO: add Func<> support.");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            return services;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("AttributedDiGeneratedServiceCollectionExtensions.g.cs", builder.ToString());
    }
}