<Project>
  <Target Name="PrepareE2EFeed" BeforeTargets="_GetRestoreSettings;Restore" Condition="'$(DesignTimeBuild)' != 'true'">
    <PropertyGroup>
      <E2EPackVersion>$(E2EPackVersionPrefix).$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmssfff"))</E2EPackVersion>
    </PropertyGroup>
    <MakeDir Directories="$(E2ELocalFeed);$(E2EGlobalPackages)" />
    <Exec Command="dotnet pack &quot;$(AttributedDIPackProject)&quot; -c Release -o &quot;$(E2ELocalFeed)&quot; -p:PackageVersion=$(E2EPackVersion)" />
  </Target>
</Project>
