using Microsoft.Extensions.DependencyInjection;
using System;
using System.Reflection;
namespace AttributedDI
{
    /// <summary>
    /// Extension methods on <see cref="IServiceCollection"/> to register services marked with <see cref="RegisterBase"/> family of attributes.
    /// </summary>
    /// <remarks>
    /// The actual registration methods are generated by the source generator at compile time.
    /// </remarks>
    public static partial class RegistrationServiceCollectionExtensions
    {
        /// <summary>
        /// Scans an assembly containing <typeparamref name="T"/> for types marked with registration attributes and registers them in <paramref name="services"/>.
        /// </summary>
        /// <typeparam name="T">Type located in assembly with services to be registered.</typeparam>
        /// <param name="services">Services collection to register services into.</param>
        /// <returns>Services collection to chain multiple calls.</returns>
        public static IServiceCollection AddServicesFromAssemblyContaining<T>(this IServiceCollection services)
        {
            return AddServicesFromAssemblies(services, typeof(T).Assembly);
        }
        /// <summary>
        /// Scans an assembly containing <paramref name="type"/> for types marked with registration attributes and registers them in <paramref name="services"/>.
        /// </summary>
        /// <param name="services">Services collection to register services into.</param>
        /// <param name="type">Type located in assembly with services to be registered.</param>
        /// <returns>Services collection to chain multiple calls.</returns>
        public static IServiceCollection AddServicesFromAssemblyContaining(this IServiceCollection services, Type type)
        {
            return AddServicesFromAssemblies(services, type.Assembly);
        }
        // AddServicesFromAssemblies and AddServicesFrom{AssemblyName} methods are generated by the source generator
    }
}